{{- if .Values.nemoGuardrails.enabled }}
{{- $o := .Values.nemoGuardrails.orchestrator -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $o.service.name }}
  labels:
    {{- include "nvidia-blueprint-rag.labels" . | nindent 4 }}
    app.kubernetes.io/component: guardrails-orchestrator
spec:
  type: {{ $o.service.type | default "ClusterIP" }}
  selector:
    {{- include "nvidia-blueprint-rag.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: guardrails-orchestrator
  ports:
    - port: {{ $o.service.port }}
      targetPort: {{ $o.service.port }}
      protocol: TCP
      name: http
{{- end }}
