{{- if and .Values.nemoGuardrails.enabled .Values.nemoGuardrails.jailbreakDetect.enabled }}
{{- $g := .Values.nemoGuardrails.jailbreakDetect -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $g.service.name }}
  labels:
    {{- include "nvidia-blueprint-rag.labels" . | nindent 4 }}
    app.kubernetes.io/component: nemoguard-jailbreak
spec:
  type: {{ $g.service.type | default "ClusterIP" }}
  selector:
    {{- include "nvidia-blueprint-rag.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nemoguard-jailbreak
  ports:
    - port: {{ $g.service.port }}
      targetPort: {{ $g.service.port }}
      protocol: TCP
      name: http
{{- end }}
