{{- if and .Values.nemoGuardrails.enabled .Values.nemoGuardrails.contentSafety.enabled .Values.nemoGuardrails.contentSafety.persistence.enabled }}
{{- $g := .Values.nemoGuardrails.contentSafety -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $g.service.name }}-cache
  labels:
    {{- include "nvidia-blueprint-rag.labels" . | nindent 4 }}
    app.kubernetes.io/component: nemoguard-content-safety
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $g.persistence.size | default "50Gi" }}
  {{- if $g.persistence.storageClass }}
  storageClassName: {{ $g.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
