{{- if and .Values.nemoGuardrails.enabled .Values.nemoGuardrails.topicControl.enabled }}
{{- $g := .Values.nemoGuardrails.topicControl -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $g.service.name }}
  labels:
    {{- include "nvidia-blueprint-rag.labels" . | nindent 4 }}
    app.kubernetes.io/component: nemoguard-topic-control
spec:
  type: {{ $g.service.type | default "ClusterIP" }}
  selector:
    {{- include "nvidia-blueprint-rag.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nemoguard-topic-control
  ports:
    - port: {{ $g.service.port }}
      targetPort: {{ $g.service.port }}
      protocol: TCP
      name: http
{{- end }}
